architect:
  - msuret
  - ochedru
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
docker:
  image: "maven:3-jdk-13"
env:
  GPG_TTY: "$(tty)"
release:
  commanders:
    - msuret
    - ochedru
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy --settings /home/r/settings.xml
